---
- name: Install {{ lb_payload }}
  yum:
    name: "{{ lb_payload }}"
    state: latest

- name: enable {{ lb_payload }} at boot
  service:
    name: haproxy
    state: started
    enabled: yes

- name: configure haproxy to load balance over app servers
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644
  notify:
    - restart HAproxy
